title: XR Design Handbook
description: a Compilation of XR Design Guidelines 🚀
theme: just-the-docs

url: https://www.xrdesignhandbook.com/

aux_links:
  Check out our repository!: https://github.com/jackyangzzh/XR-Design-Handbook
