title: XR Design Handbook
description: a collection of readme files summarizing XR design principles from various companies
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/jackyangzzh/XR-Design-Handbook
